### Many-body Entanglement and Tensor Networks
Tutorials based on the 2017 Perimeter Scholar International Condensed Matter Review course taught by Guifre Vidal

# <span style="color:#0C45A9">Python tutorial 1</span>

This notebook will first walk you through some Python basics. Then it will show you how to work with tensors and do certain tensor operations, as well as solving the eigenvalue problem.

## 1.1. Number types

In [1]:
a = 1 #integer
print("The type of 'a' is: ", type(a).__name__)

b = 3.14 #float
print("The type of 'b' is: ", type(b).__name__)

c = 1 + 2j #complex
print("The type of 'c' is: ", type(c).__name__)

The type of 'a' is:  int
The type of 'b' is:  float
The type of 'c' is:  complex


### 1.1.2. More on complex numbers

In [2]:
print("'c' has real part %s, and imaginary part %s" %(c.real, c.imag))

'c' has real part 1.0, and imaginary part 2.0


Multiplying complex numbers is straight-forward

In [3]:
z1 = complex(5,3) #alternative definition of complex numbers on Python
z2 = complex(2,4)

z3 = z1*z2
print("The product of %s and %s is %s" %(z1,z2,z3))

The product of (5+3j) and (2+4j) is (-2+26j)


Working with polar coordinates is also easy

In [4]:
import cmath

r1, theta1 = cmath.polar(z1)
r2, theta2 = cmath.polar(z2)

r3 = r1*r2
theta3 = theta1 + theta2
z3 = cmath.rect(r3,theta3)

print("The product of %s and %s is %s" %(z1,z2,z3))

The product of (5+3j) and (2+4j) is (-1.9999999999999951+26.000000000000004j)


## 1.2. Vectors, matrices and tensors

It is convenient to work with the _numpy_ library and built-in _numpy_ functions.

In [5]:
import numpy as np

vect = np.array([1,2,3])
print("Vector:", vect)

#random vector
random_vect = np.random.rand(3) #the input is the dimensions of the indeces (just one value for vectors)
print("Random vector: ", random_vect)

#complex vectors
complex_vect = np.random.rand(3) + np.random.rand(3)*1j
print("Complex vector: ", complex_vect)

Vector: [1 2 3]
Random vector:  [0.04146637 0.06787135 0.52974484]
Complex vector:  [0.03952222+0.63381722j 0.43064786+0.19304179j 0.8521259 +0.96060921j]


This can be easily generalised to matrices and higher rank tensors:

In [6]:
matrix = np.random.rand(3,3) #3x3 matrix with random entries
print("Random 3x3 matrix: \n %s \n" %(matrix))

complex_matrix = np.random.rand(2,2) + np.random.rand(2,2)*1j #2x2 matrix with complex entries
print("Random 2x2 complex matrix: \n %s \n" %(complex_matrix))

complex_tensor = np.random.rand(2,2,2) + np.random.rand(2,2,2)*1j #2x2x2 tensor with complex entries
print("Random complex rank-3 tensor: \n %s" %(complex_tensor))

Random 3x3 matrix: 
 [[0.95032773 0.01111104 0.92481503]
 [0.96138376 0.68569978 0.51120703]
 [0.96441029 0.5155953  0.34882744]] 

Random 2x2 complex matrix: 
 [[0.01574503+0.93283509j 0.33599509+0.32252532j]
 [0.57768788+0.9061519j  0.59470599+0.50823113j]] 

Random complex rank-3 tensor: 
 [[[0.79875196+0.49431022j 0.19711714+0.29652946j]
  [0.64901131+0.06614763j 0.03954571+0.0366542j ]]

 [[0.56697093+0.02388879j 0.29823362+0.1669452j ]
  [0.35400679+0.18706837j 0.22120327+0.1601003j ]]]


### 1.2.1. Indexing and slicing tensors

#### Indexing:

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Matrix: \n %s \n" %(matrix))

i = 0
matrix_row = matrix[i] #index i'th row of a matrix
print("Matrix %s'th row: %s" %(i, matrix_row))

matrix_column = matrix[:,i] #index i'th column of a matrix
print("Matrix %s'th column: %s" %(i, matrix_column))

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Matrix 0'th row: [1 2 3]
Matrix 0'th column: [1 4 7]


#### Slicing: <br>
_(NB: first slicing index not included)_

In [8]:
vect = np.array([-2,-1,0,1,2])
vect_slice = vect[2:5] #slice from element 2 til 5
print("Slice 2:5 of vector %s: \n %s " %(vect, vect_slice))

Slice 2:5 of vector [-2 -1  0  1  2]: 
 [0 1 2] 


Slicing higher-rank tensors is also simple:

In [9]:
print("Matrix: \n %s \n" %(matrix))

matrix_slice = matrix[1:3,1:3]
print("Slice [1:2,2:3] (bottom right 2x2) of matrix: \n %s " %(matrix_slice))

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Slice [1:2,2:3] (bottom right 2x2) of matrix: 
 [[5 6]
 [8 9]] 


### 1.2.2. Transposing tensors

We can use the ndarray._transpose(indeces)_ method or, equivalently, the _transpose(ndarray, indeces)_ function. <br>
The argument _indeces_ specifies the permutation used to transpose the tensor. If not specified, defaults to range(a.ndim)[::-1], which completely reverses the order. In this case, the shortcut method _.T_ can be used.

In [10]:
print("Matrix: \n %s \n" %(matrix))

matrix_trans1 = matrix.transpose(1,0)
matrix_trans2 = matrix.T
print("Methods match: ", (np.allclose(matrix_trans1,matrix_trans2)))
print("Transposed matrix: \n", matrix_trans1)

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Methods match:  True
Transposed matrix: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
tensor = np.random.rand(2,2,2)
print("Tensor: \n %s \n" %(tensor))

tensor_trans = tensor.transpose(0,2,1) #transpose last 2 indeces
print("Transposed tensor: \n", tensor_trans)

#we don't expect this to match with the .T shortcut
print("\n Methods match: ", (np.allclose(tensor_trans,tensor.T)))

Tensor: 
 [[[0.4207849  0.97685537]
  [0.90327353 0.86110961]]

 [[0.21637027 0.68185991]
  [0.57400025 0.7014877 ]]] 

Transposed tensor: 
 [[[0.4207849  0.90327353]
  [0.97685537 0.86110961]]

 [[0.21637027 0.57400025]
  [0.68185991 0.7014877 ]]]

 Methods match:  False


#### Hermitian conjugate (cojugate + transpose)

In [12]:
print("Complex matrix: \n %s \n" %(complex_matrix))
print("Hermitian conjugate of matrix: \n", complex_matrix.conj().T)

Complex matrix: 
 [[0.01574503+0.93283509j 0.33599509+0.32252532j]
 [0.57768788+0.9061519j  0.59470599+0.50823113j]] 

Hermitian conjugate of matrix: 
 [[0.01574503-0.93283509j 0.57768788-0.9061519j ]
 [0.33599509-0.32252532j 0.59470599-0.50823113j]]


### 1.2.3. Tensor norm

The _np.linalg.norm()_ function allows us to calculate different order norms for tensors. For example, the 2-norm:

In [13]:
vect = np.array([-2,-1,1,2])
vect_norm = np.linalg.norm(vect)
print("Norm for vector %s is: %s" %(vect, vect_norm))

matrix = np.reshape(vect, (2,2))
matrix_norm = np.linalg.norm(matrix)
print("Norm for matrix \n %s \n is: %s" %(matrix, matrix_norm))

Norm for vector [-2 -1  1  2] is: 3.1622776601683795
Norm for matrix 
 [[-2 -1]
 [ 1  2]] 
 is: 3.1622776601683795


### 1.2.4. Tensor products

It is useful to learn how to use the general function _np.tensordot()_ to conveniently do tensor product operations by specifying the indeces over which the operation takes place. In some instances there exist simpler functions. We will see some example with vectors and matrices, which can be generalised to higher-rank tensors.

#### Vectors

Given two vectors $v, u$ of dimension $m, n$ respectively:
1. Outer (Kronecker) product:
$~~~~v \otimes u = \left[ \begin{array}{cc} 
v_{1} u_1 & v_{1}u_2 &\cdots& v_1 u_n \\ 
v_{2} u_1 & v_{2}u_2 &\cdots& v_{2} u_n \\
\vdots & \vdots & \cdots & \vdots \\
v_{m} u_1 & v_mu_2 &\cdots& v_m u_n
\end{array} \right]$ <br>
<br>
2. Dot product: $v\cdot u = v_1u_1 + v_2u_2 \cdots v_m u_n$

In [14]:
v = np.array([1,2,3])
u = np.array([4,5,6])
print("Vectors: %s , %s \n" %(v,u))

#1. Vector outer product (results in a matrix)
outer_prod = np.tensordot(v, u, axes=0)
print("Outer product: \n %s \n" %(outer_prod))

#2. Vector dot product (results in a scalar)
dot_prod = np.tensordot(v, u, axes=1)
print("Dot product: %s" %(dot_prod))

Vectors: [1 2 3] , [4 5 6] 

Outer product: 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 

Dot product: 32


#### Matrix

Given two matrices $A,B$ with shapes $m\times n$ and $q \times p$ respectively:

1. Outer (Kronecker) product:
$~~~~A \otimes B = \left[ \begin{array}{cc} 
a_{11} B & a_{12}B &\cdots& a_{1n} B \\ 
a_{21} B & a_{22}B &\cdots& a_{2n} B \\
\vdots & \vdots & \cdots & \vdots \\
a_{m1} B & a_{m2}B &\cdots& a_{mn} B
\end{array} \right]$ <br>
<br>
2. Standard matrix product ($n=q$ and result is $m\times p$):
$~~~~AB = C$ where $c_{ij} = a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots +a_{in}b_{n_j} = \sum_{k=1}^na_{ik}b_{kj}$. <br>
<br>
3. Element-wise product ($m=q, n=p$): 
$~~~~AB = a_{11}b_{11}+a_{12}b_{12}+\cdots+ a_{mn}b_{mn}$.

In [15]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,0,1],[0,1,0]]).T
print("Matrices: \n A = %s \n B= %s \n" %(A,B))

# 1. Outer product 
#two ways
outer_prod1 = np.tensordot(A,B, axes = 0).transpose(0,2,1,3).reshape(6,6)
outer_prod2 = np.kron(A,B) #simpler
if np.allclose(outer_prod1,outer_prod2):
    print("Outer product: \n %s \n" %(outer_prod2))
    
# 2. Standard matrix product
#three ways
stand_prod1 = np.tensordot(A, B, axes = (1,0))
stand_prod2 = np.matmul(A, B)
stand_prod3 = A.dot(B)
if np.allclose(stand_prod1, stand_prod2, stand_prod3):
    print("Standard product: \n %s \n" %(stand_prod3))
    
# 3. Element-wise product
B = B.T #transpose for dimensions to match
element_prod = np.tensordot(A, B, axes = 2)
print("Element-wise product: %s" %(element_prod))

Matrices: 
 A = [[1 2 3]
 [4 5 6]] 
 B= [[1 0]
 [0 1]
 [1 0]] 

Outer product: 
 [[1 0 2 0 3 0]
 [0 1 0 2 0 3]
 [1 0 2 0 3 0]
 [4 0 5 0 6 0]
 [0 4 0 5 0 6]
 [4 0 5 0 6 0]] 

Standard product: 
 [[ 4  2]
 [10  5]] 

Element-wise product: 9


## 1.3. Eigenvalues and eigenvectors

The _numpy_ function _linalg.eig()_ returns:
- D: array with the eigenvalues (diagonal entries of the similar matrix)
- U: matrix containing the normalised eigenvectors in its columns, such that U[:,i] is the eigenvector corresponding to eigenvalue D[i].

In [16]:
Z = np.array([[1,0],[0,-1]])
print("Pauli Z matrix: \n %s \n" %(Z))

D, U = np.linalg.eig(Z)
print("Eigenvalues: %s \nEigenvectors: %s, %s" %(D, U[:,0], U[:,1]))

Pauli Z matrix: 
 [[ 1  0]
 [ 0 -1]] 

Eigenvalues: [ 1. -1.] 
Eigenvectors: [1. 0.], [0. 1.]


For a random hermitian matrix let's check that $M = U\cdot D \cdot U^{\dagger}$ and that $M\cdot \vec{v}_i = \lambda_i \vec{v}_i$:

In [17]:
M = np.random.rand(3,3) + np.random.rand(3,3)*1j
M = (M + M.conj().T)/2 

D, U = np.linalg.eig(M)
M_resulting = U.dot(np.diag(D)).dot(U.conj().T)

print("The eigenvalue decomposition procedure works: ", np.allclose(M,M_resulting))
print("The eigenvalue equation holds (eigenvalue i=1): ", np.allclose(np.dot(M,U[:,0]), D[0]*U[:,0]))

The eigenvalue decomposition procedure works:  True
The eigenvalue equation holds (eigenvalue i=1):  True
